name: Go Build and Release

on:
  push:
    tags:
      - '*.*.*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            go.mod
            go.sum
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy  # This command should be executed before build

      - name: Build binary
        run: go build -o ghm main.go

      - name: Run tests
        run: go test ./...

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghm-binary
          path: ./ghm

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Install dependencies
        run: go mod tidy  # Ensure go.sum is generated in the release job too

      - name: Build binary
        run: go build -o ghm main.go

      - name: Check if GITHUB_TOKEN is available
        run: |
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "GH_TOKEN is not available. Skipping release step."
            exit 0
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: ./ghm
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}