name: Go Build

on:
  push:
    tags:
      - '*.*.*'
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            go.mod
            go.sum
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Build binary
        run: go build -v -o ghm

      # - name: Run tests
      #   run: go test ./...

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghm-binary
          path: ./ghm

      # - name: Commit built binary back to the repository
      #   run: |
      #     git config user.name "GitHub Actions"
      #     git config user.email "actions@github.com"
      #     git add .
      #     git commit -m "Add built binary ghm"
      #     git push origin main
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}